### PR TITLE
Fix missing comma and remove invalid trailing comma

### PR DESCRIPTION
**Pull request by therealbluepandabear**

### CODE REVIEW

**Comment by ichordev** [comment]
Not sure if the JSON spec disallows it, but dub.json files allow trailing commas.

**Comment by therealbluepandabear** [comment]
> Not sure if the JSON spec disallows it, but dub.json files allow trailing commas.

Well that trailing comma gave me an error.

**Comment by ichordev** [comment]
> Well that trailing comma gave me an error. Try it yourself to double check.

I already did. What's your OS and dub version? What is the error you get?

**Comment by therealbluepandabear** [comment]
Copying and pasting your code gives me this:

image

image

I have the latest dub version.

**Comment by ichordev** [comment]
> Copying and pasting your code gives me this:
> 
> image
> 
> image
> 
> I have the latest dub version.

This is not an error from dub.

**Comment by therealbluepandabear** [comment]
> > Copying and pasting your code gives me this:
> > image
> > image
> > I have the latest dub version.
> 
> This is not an error from dub.
Yes but it is a warning, it's good to have code on the repo which does not produce warnings (which mine doesn't).

**Comment by ichordev** [comment]
> it's good to have code on the repo which does not produce warnings

These warnings come from a third-party tool, they are meaningless. There are a myriad of broken third-party tools which will produce erroneous warnings. Their output should not be used as the basis for making changes.

Are there are reliable resources for dub that suggest that allowing trailing commas is unintentional and/or is subject to removal/change? Maybe ask some dub contributors if you can't find anything.

**Comment by therealbluepandabear** [comment]
Unfortunately I cannot keep trying to convince you to accept this pull request.

Your project, your decision.

**Comment by ichordev** [comment]
> Unfortunately I cannot keep trying to convince you to accept this pull request.
> 
> Your project, your decision.

The SFML readme will be rewritten at some point in the future anyway. I have no problem with fixing the missing comma, but removing the trailing comma just seems unnecessary unless there's some reason it's not going to work in the future.

**Pull request closed without merging**
